platform: linux
inputs:
- name: cd-k8s
image_resource:
    type: docker-image
    source:
      repository: chihebdk/cloudtools
      tag: latest
run:
  path: cd-k8s/kubernetes/scripts/install-jenkins.sh