---
resources:
- name: my-resource
  type: git
  source:
    branch: master
    uri: https://github.com/chihebdk/jenkins-on-k8s-pipeline.git

jobs:
- name: Run-automatically
  plan:
  - get: my-resource
    trigger: true
  - task: do-your-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This job is automatically triggered upon any version change in the resource."







