resources:
- name: cd-k8s
  type: git
  source:
    uri: https://github.com/chihebdk/jenkins-on-k8s-pipeline.git
    branch: master

jobs:
- name: jenkins-setup
  public: true
  plan:
    - get: cd-k8s
      trigger: true
    - task: create-cluster
      file: cd-k8s/kubernetes/tasks/create-cluster.yaml







