resources:
- name: jenkins-on-k8s-pipeline
  type: git
  source:
    uri: https://github.com/chihebdk/jenkins-on-k8s-pipeline.git
    branch: master

jobs:
- name: jenkins-setup
  public: true
  plan:
    - get: jenkins-on-k8s-pipeline
      trigger: true
    - task: create-cluster
      file: jenkins-on-k8s-pipeline/kubernetes/tasks/create-cluster.yaml
      params:        
        AWS_ACCESS_KEY_ID: ((AWS_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_ACCESS))
 







