resources:
- name: jenkins-on-k8s-pipeline
  type: git
  source:
    uri: https://github.com/chihebdk/jenkins-on-k8s-pipeline.git
    branch: master

jobs:
- name: create-cluster
  public: true
  plan:
    - get: jenkins-on-k8s-pipeline
      trigger: true
    - task: create-cluster
      file: jenkins-on-k8s-pipeline/kubernetes/tasks/create-cluster.yaml
      params:        
        AWS_ACCESS_KEY_ID: ((AWS_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_ACCESS))
        AWS_DEFAULT_REGION:  us-east-1
        CLUSTER_NAME: ((CLUSTER_NAME))
        KOPS_STATE_STORE: ((KOPS_STATE_STORE))

- name: install-tools
  public: true
  plan:
    - get: jenkins-on-k8s-pipeline
      trigger: true
    - task: install-tools
      file: jenkins-on-k8s-pipeline/kubernetes/tasks/install-tools.yaml
      params:        
        AWS_ACCESS_KEY_ID: ((AWS_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_ACCESS))
        AWS_DEFAULT_REGION:  us-east-1
        CLUSTER_NAME: ((CLUSTER_NAME))
        KOPS_STATE_STORE: ((KOPS_STATE_STORE))

- name: delete-cluster
  public: true
  plan:
    - get: jenkins-on-k8s-pipeline
      trigger: false
    - task: delete-cluster
      file: jenkins-on-k8s-pipeline/kubernetes/tasks/delete-cluster.yaml
      params:        
        AWS_ACCESS_KEY_ID: ((AWS_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_ACCESS))
        AWS_DEFAULT_REGION:  us-east-1
        CLUSTER_NAME: ((CLUSTER_NAME))
        KOPS_STATE_STORE: ((KOPS_STATE_STORE))






